package com.soundmatt.jfusa.release;

import com.soundmatt.jfusa.FuSa;
import com.soundmatt.jfusa.FuSa.Finding;
import com.soundmatt.jfusa.FuSa.Severity;
import com.soundmatt.jfusa.config.Config;
import com.soundmatt.jfusa.engine.Engine;
import com.soundmatt.jfusa.engine.Rule;
import com.soundmatt.jfusa.internal.Json;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.HexFormat;
import java.util.List;

/**
 * SBOM generation (SPDX 2.3), build provenance, and artifact manifest.
 */
public final class Release {

    public static final String SBOM_FILE       = "sbom.json";
    public static final String PROVENANCE_FILE = "provenance.json";
    public static final String MANIFEST_FILE   = "artifact-manifest.json";

    static {
        Engine.DEFAULT.mustRegister(new RuleSBOMPresent());
        Engine.DEFAULT.mustRegister(new RuleProvenancePresent());
    }

    private Release() {}
    public static void activate() {}

    // ── SBOM (SPDX 2.3) ───────────────────────────────────────────────────────

    public static void generateSBOM(Path projectRoot, Config cfg) throws IOException {
        String name = cfg != null ? cfg.project().name() : "unknown";
        String version = FuSa.VERSION;
        var w = new Json.Writer();
        w.objectStart();
        w.field("SPDXID", "SPDXRef-DOCUMENT");
        w.field("spdxVersion", "SPDX-2.3");
        w.field("name", name + "-sbom");
        w.field("dataLicense", "CC0-1.0");
        w.field("documentNamespace", "https://github.com/SoundMatt/java-FuSa/sbom/" + Instant.now().toEpochMilli());
        w.field("created", Instant.now().toString());
        w.field("creatorComment", "Generated by java-FuSa v" + FuSa.VERSION + " (x-FuSa spec " + FuSa.SPEC_VERSION + ")");
        w.key("creators"); w.arrayStart();
        w.value("Tool: java-FuSa-" + FuSa.VERSION);
        w.arrayEnd();
        w.key("packages"); w.arrayStart();
        w.objectStart();
        w.field("SPDXID", "SPDXRef-Package");
        w.field("name", name);
        w.field("versionInfo", version);
        w.field("downloadLocation", "NOASSERTION");
        w.field("filesAnalyzed", false);
        w.field("licenseConcluded", "MPL-2.0");
        w.field("licenseDeclared", "MPL-2.0");
        w.field("copyrightText", "NOASSERTION");
        w.objectEnd();
        w.arrayEnd();
        w.objectEnd();
        Files.writeString(projectRoot.resolve(SBOM_FILE), w.toPretty() + "\n");
    }

    // ── Build provenance ──────────────────────────────────────────────────────

    public static void generateProvenance(Path projectRoot, Config cfg) throws IOException {
        var w = new Json.Writer();
        w.objectStart();
        w.field("_type", "https://in-toto.io/Statement/v0.1");
        w.field("predicateType", "https://slsa.dev/provenance/v0.2");
        w.key("subject"); w.arrayStart(); w.arrayEnd();
        w.key("predicate"); w.objectStart();
        w.key("builder"); w.objectStart();
        w.field("id", "https://github.com/SoundMatt/java-FuSa");
        w.objectEnd();
        w.field("buildType", "https://github.com/SoundMatt/java-FuSa/maven");
        w.key("invocation"); w.objectStart();
        w.key("configSource"); w.objectStart();
        w.field("uri", "pom.xml");
        w.objectEnd();
        w.objectEnd();
        w.key("metadata"); w.objectStart();
        w.field("buildStartedOn", Instant.now().toString());
        w.field("completeness"); w.objectStart();
        w.field("parameters", false);
        w.field("environment", false);
        w.field("materials", false);
        w.objectEnd(); // completeness
        w.objectEnd(); // metadata
        w.objectEnd(); // predicate
        w.objectEnd();
        Files.writeString(projectRoot.resolve(PROVENANCE_FILE), w.toPretty() + "\n");
    }

    // ── Artifact manifest ─────────────────────────────────────────────────────

    public static void generateManifest(Path projectRoot, List<String> artifacts) throws IOException {
        var w = new Json.Writer();
        w.objectStart();
        w.field("schema", "x-fusa-manifest-1.0");
        w.field("timestamp", Instant.now().toString());
        w.key("artifacts"); w.arrayStart();
        for (String art : artifacts) {
            Path p = projectRoot.resolve(art);
            if (Files.exists(p)) {
                w.objectStart();
                w.field("path", art);
                w.field("sha256", sha256file(p));
                w.field("sizeBytes", Files.size(p));
                w.objectEnd();
            }
        }
        w.arrayEnd();
        w.objectEnd();
        Files.writeString(projectRoot.resolve(MANIFEST_FILE), w.toPretty() + "\n");
    }

    static String sha256file(Path p) throws IOException {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] bytes = Files.readAllBytes(p);
            return "sha256:" + HexFormat.of().formatHex(md.digest(bytes));
        } catch (Exception e) {
            return "";
        }
    }

    // ── Rules ─────────────────────────────────────────────────────────────────

    static final class RuleSBOMPresent implements Rule {
        public String id() { return "RELEASE001"; }
        public String description() { return "SBOM (sbom.json) must be present for supply-chain compliance."; }

        //fusa:req REQ-RELEASE001
        public List<Finding> run(Path root, Config cfg) {
            if (!Files.exists(root.resolve(SBOM_FILE))) {
                return List.of(Finding.builder("RELEASE001", Severity.WARNING,
                        "no sbom.json found — run 'jfusa release' to generate",
                        new FuSa.Location(SBOM_FILE))
                        .category(FuSa.Category.SUPPLY_CHAIN)
                        .standard("SLSA").clause("L2")
                        .remediation("run 'jfusa release' to generate SBOM and provenance")
                        .build());
            }
            return List.of();
        }
    }

    static final class RuleProvenancePresent implements Rule {
        public String id() { return "RELEASE002"; }
        public String description() { return "Build provenance (provenance.json) must be present for SLSA compliance."; }

        //fusa:req REQ-RELEASE002
        public List<Finding> run(Path root, Config cfg) {
            if (!Files.exists(root.resolve(PROVENANCE_FILE))) {
                return List.of(Finding.builder("RELEASE002", Severity.WARNING,
                        "no provenance.json found — run 'jfusa release' to generate",
                        new FuSa.Location(PROVENANCE_FILE))
                        .category(FuSa.Category.SUPPLY_CHAIN)
                        .standard("SLSA").clause("L2")
                        .remediation("run 'jfusa release' to generate build provenance")
                        .build());
            }
            return List.of();
        }
    }
}
