package com.soundmatt.jfusa.sas;

import com.soundmatt.jfusa.FuSa;
import com.soundmatt.jfusa.internal.Json;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;

/**
 * Software Accomplishment Summary — DO-178C §11.20.
 * Generates sas.md summarizing all lifecycle data items and their status.
 */
public final class Sas {

    public static final String SAS_MD = "sas.md";

    private static final List<String[]> LIFECYCLE_DATA = List.of(
        new String[]{"Plan for Software Aspects of Certification (PSAC)", "11.1",  ".fusa.json"},
        new String[]{"Software Development Plan (SDP)",                   "11.4",  ".fusa.json"},
        new String[]{"Software Requirements Standards",                   "11.6",  ".fusa-reqs.json"},
        new String[]{"Software Design Standards",                         "11.7",  ".fusa.json"},
        new String[]{"Software Code Standards",                           "11.9",  ".fusa.json"},
        new String[]{"Software Requirements Data (HLR)",                  "11.10", ".fusa-reqs.json"},
        new String[]{"Software Design Description (LLR)",                 "11.11", "safety-case.json"},
        new String[]{"Source Code",                                        "11.12", "pom.xml"},
        new String[]{"Executable Object Code",                             "11.13", "target/jfusa.jar"},
        new String[]{"Software Verification Plan",                         "11.5",  ".fusa.json"},
        new String[]{"Software Verification Results",                      "11.14", "qualify-report.json"},
        new String[]{"Software Configuration Management Plan",             "11.3",  ".fusa.json"},
        new String[]{"Software Quality Assurance Plan",                    "11.2",  ".fusa.json"},
        new String[]{"Software Configuration Index (SCI)",                 "11.16", "sci.json"},
        new String[]{"Problem Reports",                                    "11.17", ".fusa-problems.json"},
        new String[]{"Software Life Cycle Environment Configuration",      "11.15", "sbom.json"},
        new String[]{"Additional Considerations",                          "11.21", "CHANGELOG.md"}
    );

    private Sas() {}

    public static void generate(Path root) throws IOException {
        var sb = new StringBuilder();
        sb.append("# Software Accomplishment Summary\n\n");
        sb.append("**Standard:** DO-178C §11.20  \n");
        sb.append("**Tool:** jfusa v").append(FuSa.VERSION).append("  \n");
        sb.append("**Generated:** ").append(Instant.now()).append("\n\n");
        sb.append("## Lifecycle Data Items\n\n");
        sb.append("| Lifecycle Data Item | §11 Ref | File | Status |\n");
        sb.append("|---|---|---|---|\n");

        int present = 0, total = LIFECYCLE_DATA.size();
        for (String[] item : LIFECYCLE_DATA) {
            Path p = root.resolve(item[2]);
            boolean exists = Files.exists(p);
            if (exists) present++;
            sb.append("| ").append(item[0]).append(" | ")
              .append(item[1]).append(" | `").append(item[2]).append("` | ")
              .append(exists ? "Present" : "Missing").append(" |\n");
        }

        sb.append("\n## Summary\n\n");
        sb.append(String.format("- Total lifecycle data items: **%d**%n", total));
        sb.append(String.format("- Present: **%d** (%.0f%%)%n", present, 100.0 * present / total));
        sb.append(String.format("- Missing: **%d**%n", total - present));
        sb.append("\n## Certification Basis\n\n");
        sb.append("This SAS was generated by jfusa v").append(FuSa.VERSION)
          .append(" in accordance with DO-178C, DAL per project configuration.\n");
        sb.append("All evidence artifacts can be bundled via `jfusa audit-pack`.\n");

        Files.writeString(root.resolve(SAS_MD), sb.toString());
        System.out.println("SAS generated: " + SAS_MD + " (" + present + "/" + total + " items present)");
    }
}
